auto: true
server: true
url: http://cobyism.com/
permalink: /articles/:title/
handle: cobyism
gravatar_hash: ee5bae7fa46b3195869c285ecbb4619e
gauges_id: 4fcd8fbef5a1f558c6000046
google_analytics_id: UA-31312255-1
